### PR TITLE
Adding 10 Iterations of Maps

### PR DESCRIPTION
**Pull request by yourior**
adding maps via prefab, and maps via tile palette

### CODE REVIEW

**Review by mmgfrcs — CHANGES_REQUESTED** [review]
- Remove and then ignore the `.vscode` folder
- Review ProjectSettings change
- Will's File folder not needed. Sort it out on the appropriate top-level folder
- Tile Prefabs should be in Prefabs folder

**Comment by yourior** [comment]
removed will's file
removed .vscode
updated ProjectSettings to latest pull
moved all prefab to prefab file

all the removed file already ignored for future pull

**Comment by yourior** [comment]
fix map 
added 6 towers sprite with tip

**Review by mmgfrcs — APPROVED** [review]
No more irrelevant changes, and thus approved for merge

**Pull request merged**
