### PR TITLE
Fix Checkpoint Coordinates & Add Expansion Configuration

### PR DESCRIPTION
**Pull request by yourior**

### CODE REVIEW

**Review by mmgfrcs — CHANGES_REQUESTED** [review]
The coordinates for the checkpoints and the tower spots are still empty

**Comment by yourior** [comment]
yep... i'll wait for the script to be fixed first , since usually when the script is edited, the data tend to be overwritten

**Comment by mmgfrcs** [comment]
No need, that part of the script is untouched

**Review by mmgfrcs — APPROVED** [review]
Coordinates are now included and ready for use

**Pull request merged**
